### PR TITLE
Merge TeX

### PR DESCRIPTION
**Pull request by nickmcintyre**
This pull request restores the `TeX` object. I extended the example sketch to include its use. No tests yet – what are your thoughts @two-ticks?

### CODE REVIEW

**Comment by two-ticks** [comment]
I wanted to know about workflow. Should I make a pull request to your branch or work after the code been merged into 'develop'? 

One way: I think we can merge, then can fix some bugs and add test cases along with working on other features. 
Another way: we can also try fixing some obvious bugs then merging. 

About test cases, I think we can add test in the pull request itself so that we don't procrastinate test for long. (I have made really less test cases, I will try to add more)

We can add more documentation and can go for feedback as soon as we have some working features (Text, TeX, and Shapes), then we can work on editor and can try out more possibilities.

**Comment by nickmcintyre** [comment]
@two-ticks sure, go ahead and make the pull request to my branch so we can try keeping `develop` clean.

**Comment by two-ticks** [comment]
I think pull request is pointing to incorrect branch. I think pull request should be merged in `develop` rather than `main`, it is currently pointing to `main`. @JithinKS97 What is your thought on it?

**Comment by nickmcintyre** [comment]
Let's close this pull request and open a new one based on the `merge-TeX-fixing` branch.

**Pull request closed without merging**
