### PR TITLE
IBM's color blind safe palette

### PR DESCRIPTION
**Pull request by two-ticks**
- [x] color blind safe palette exported

### CODE REVIEW

**Review by nickmcintyre — COMMENTED** [review]
Nice! Mind adding an example sketch?

**Comment by two-ticks** [comment]
https://editor.p5js.org/radium.scientist/sketches/oAhcBTQgz

- [x] sketch added
- [x] unique id to each arrow 
- [x] safeColor object 

```processing
safeColor = {
  ULTRAMARINE40: "#648fff",
  MAGENTA50: "#dc267f",
  GOLD20: "#ffb000",
  INDIGO50: "#785ef0",
  ORANGE40: "#fe6100",
};
```
more colors to be added

**Review by nickmcintyre — COMMENTED** [review]
@JithinKS97 what do you think about the `safeColor` object? I like that it helps to keep the global scope tidy. Adding a limited number of color constants also seems OK to me - perhaps no more than there are [color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_keywords).

@two-ticks how should we present color palettes more generally? One thought is to have a function like `colorPalette(palette: string)` that sets 5 or so colors and stores them as scene variables.

**Comment by two-ticks** [comment]
I am very interested in `colorPalette(palette: string)`, can you give some more context about the argument and output? 
1. Does it set `palette` by user input ?
2. Or it provides `palette` in-built/defaults options so user can select?

**Comment by nickmcintyre** [comment]
The argument would be the name of a predefined color palette and the thought is to program for side effects.

For example, calling `colorPalette('red-blue')` would set a scene variable to something like `['#ca0020','#f4a582','#f7f7f7','#92c5de','#0571b0']` which would then be referenced to set default colors. Defaults could still be overridden with `config` objects or calls to `configure`.

[ColorBrewer](https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=5) is a nice way to generate color blind friendly palettes.

**Review by nickmcintyre — APPROVED** [review]
@two-ticks This is great! What do you think about adding a few examples from your work on the p5.js Web Editor to an `examples` folder?

**Comment by two-ticks** [comment]
@nickmcintyre  I am working on some examples would make a collection on web editor and also include them in https://github.com/two-ticks/p5.teach.js/tree/develop/assets/examples 

Something like this.
text

**Pull request merged**
